name: Deploy to VPS

on:
  push:
    branches:
      - main  # Замените на вашу ветку, если необходимо

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github_actions
        chmod 600 ~/.ssh/id_rsa_github_actions

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Sync files to server
      run: |
        ssh -vvv username@${{ secrets.SERVER_IP }}



    - name: Run deployment commands
      run: |
        ssh username@${{ secrets.SERVER_IP }} << 'EOF'
          source /project/ChatBot/myprojectenv/bin/activate
          cd $PROJECT_DIR
          python manage.py collectstatic --noinput
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
        EOF