name: Deploy to VPS

on:
  push:
    branches:
      - main  # Замените на вашу ветку, если необходимо

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add VPS to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Debug SSH Connection
      run: |
        echo "Attempting to connect to daniil@${{ secrets.SERVER_IP }}"
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -vvv daniil@${{ secrets.SERVER_IP }} "echo 'Connected successfully!'"

    - name: Run deployment commands
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@${{ secrets.SERVER_IP }} << 'EOF'
          # Ваши команды развертывания здесь
          cd /path/to/your/project
          git pull origin main  # Или другие команды
        EOF